### ISSUE TITLE
Is it possible to have test step annotations like Allure reports have ? 

### ISSUE THREAD

**Issue by azakordonets** [reportportal/agent-java-testNG#5]
Hi, 

Not sure wheather i should write into this repo or into the main one, but does report portal support anything like Allure Step annotations ? Is there any way to integrate Allure reports with ReportPortal ? https://github.com/allure-framework/allure1/wiki/Steps

**Comment by DzmitryHumianiuk** [comment]
@azakordonets hi
It's a right place for that ticket.
Since it only adapter related implementation.

Idea is pretty simple, and we can consider it as a part of `BDD strategy/Step-based strategy`
And a part of async client for Java. @avarabyeu ?

Also, you can contribute this part to our agent, and we will accept it after review

**Comment by avarabyeu** [comment]
@DzmitryHumianiuk somewhere we had already a similar question. Unfortunately no, that's no so simple and does not related to strategies. I would rather implement it as part of import functionality

**Comment by DzmitryHumianiuk** [comment]
@azakordonets 
let's clarify the need.

**option#1**
use @step annotation for name placeholders (bypassing). Like below
```java
public static final String pageAddress = "PROFILE";

@Step("Open {0} page.")
public void openPageByAddress(String pageAddress) {
     ...
 }
```
Name will be sent to RP as `Open PROFILE page`

**option#2**
you need it just for identification of step in your scenarios?

**Comment by azakordonets** [comment]
Well, in Allure reports this @Step annotations is used to depict the scenario of what happened and at which step it failed. Basically, it allows to give a nice logging of actions taken during the test, which then can be displayed in the report.

**Comment by DzmitryHumianiuk** [comment]
@azakordonets 
in order to implement the same ability for `@Step` and any others,
we need to switch our agent of Aspects (AOP).

currently TestNG context does not return object of nested methods, called during execution.

as a middle step, we will introduce `NestedSteps` object, which will cover BDD and nested steps representation at the same time.
Basically it, RP will not calculate statistics for it, but will represent it as a step of test case.

later, we will migrate to AOP agents.
but no exact dates, when we will start it.

**Comment by HardNorth** [comment]
I believe we implemented this, at last. Please look at this example: https://github.com/reportportal/examples-java/blob/master/example-junit/src/test/java/com/epam/reportportal/example/junit/NestedStepTest.java
